# Generated by Django 3.1.2 on 2020-10-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Cateogry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, null=True)),
                ('Description', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(null=True, upload_to='cateogry/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Create_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('password2', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Create_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(null=True, upload_to='post/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('cateogry', models.ManyToManyField(to='memegen.Create_Cateogry')),
            ],
        ),
    ]
