# Generated by Django 3.1.2 on 2020-11-04 03:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memegen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_cateogry',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='create_post',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
