# Generated by Django 3.1.2 on 2020-11-04 04:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memegen', '0002_auto_20201104_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_cateogry',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='create_post',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo'),
        ),
    ]
